name: IPTV-Go

on:
  workflow_dispatch:  # 允许手动执行

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: linux
            goarch: 386
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: mips
          - goos: linux
            goarch: mips64
          - goos: linux
            goarch: mipsle
          - goos: linux
            goarch: mips64le
          - goos: linux
            goarch: riscv64
          - goos: linux
            goarch: arm
            goarm: 5
          - goos: linux
            goarch: arm
            goarm: 6
          - goos: linux
            goarch: arm
            goarm: 7
          - goos: windows
            goarch: 386
          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: arm64
          - goos: android
            goarch: arm64

    steps:
      - uses: actions/checkout@v4
      - name: Cross Compile
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} GOARM=${{ matrix.goarm }} go build -o ysptp_${{ matrix.goos }}_${{ matrix.goarch }}${{ matrix.goarm }}
      - name: Upload Cross Compile Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ysptp_${{ matrix.goos }}_${{ matrix.goarch }}${{ matrix.goarm }}
          path: ysptp_${{ matrix.goos }}_${{ matrix.goarch }}${{ matrix.goarm }}