name: Sync Upstream
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Sync upstream
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git remote add upstream https://github.com/maboloshi/github-chinese.git
          git fetch upstream
          git checkout gh-pages
          git merge upstream/gh-pages
          git push https://${{ secrets.PAT }}@github.com/smjcxf/cs.git gh-pages
