name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git username
        run: git config --global user.name 'GitHub Actions'

      - name: Set Git email
        run: git config --global user.email 'actions@github.com'

      - name: Pull and switch branch
        run: |
          git remote add upstream https://github.com/maboloshi/github-chinese
          git fetch upstream
          git checkout -b gh-pages upstream/gh-pages

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}  # PAT 是在 GitHub 仓库的 Secrets 中添加的令牌名称
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/smjcxf/cs.git gh-pages
