name: Download Repository

on:
  # 可以根据需要设置触发条件，这里设置为手动触发
  workflow_dispatch:

jobs:
  download-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Download target repository
        run: |
          # 设置目标仓库的 URL
          TARGET_REPO_URL="https://github.com/bingotang1981/iptv.git"
          # 设置下载目录
          DOWNLOAD_DIR="downloaded-repo"
          # 克隆目标仓库到指定目录
          git clone $TARGET_REPO_URL $DOWNLOAD_DIR

      - name: Commit and push changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your_email@example.com"
          git add .
          git commit -m "Downloaded target repository"
          git push
