name: Download github-chinese branches

on:
  # 可以根据需要调整触发条件，比如 push 到 main 分支
  push:
    branches:
      - main

jobs:
  download-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone github-chinese repository
        run: |
          mkdir -p github-chinese
          cd github-chinese
          git clone --mirror https://github.com/maboloshi/github-chinese.git .git

      - name: Create folders for each branch and checkout
        run: |
          cd github-chinese
          for branch in $(git branch -r | grep -v 'HEAD' | grep -v 'origin/HEAD' | sed 's/origin\///'); do
            mkdir -p $branch
            git --work-tree=$branch checkout $branch
          done

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Downloaded github-chinese branches" || true
          git push
